name: Run tests
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  test:
    name: Run e2e tests
    runs-on: 	macos-12
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Run tests
        run: |
          npm install
          npm run test
